### ISSUE TITLE
Crashing on Android

### ISSUE THREAD

**Issue by JohnLins** [BK1031/StorkeCentral#65]
App opens, error message pops up: "failed to fetch dining halls," error then goes away, the app can be used for some amount of time before crashing.

The Android system says, "App closed because it has a bug" 

Sometimes, the Android system requests that you clear the cache.

I suspect that there is a run-away memory leak.

**Comment by rovirmani** [comment]
i dont have this issue. pls close lgtm.

**Comment by BK1031** [comment]
Should be fixed in the latest release, going to close for now but feel free to reopen if the problem still occurs.
